version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14

    volumes:
      - ..:/workspace:cached
      - ~:/host:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-20.04
    environment:
      - SA_PASSWORD=Local_sa
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"