# Basic code quality build/lint/test check

name: CI Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./voting-service

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
        working-directory: ${{env.WORKING_DIR}}
      - run: npm run lint
        working-directory: ${{env.WORKING_DIR}}
      - run: npm run build
        working-directory: ${{env.WORKING_DIR}}
      - run: npm test
        working-directory: ${{env.WORKING_DIR}}
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: voting-service/coverage/
        env:
          CI: true

  security:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./voting-service

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
        working-directory: ${{env.WORKING_DIR}}
      - run: npm audit --omit=dev
        working-directory: ${{env.WORKING_DIR}}
        env:
          CI: true

